export default {
    data() {
        return {
            naslov: "Sadhana XX – Sodba",
            modrostGlavna: '"To je pot duhovnega prebujenja, ki se ustvari skozi vključevanja presoje, ne pa pot presoje na duhovnem potovanju. Presojanje je aktiven mentalni proces, ki uravnoteži dva ali več možnosti in oceni posledice."',

            priprava:
                '<p>Usedite se v udoben meditacijski položaj s prekrižanimi nogami, sede na stolu ali pa kako drugače. Poskrbite, da boste lahko ves čas meditacije sedeli udobno in brez kakršnih koli večjih neprijetnosti. Zaprite oči roke položite na kolena in se začnite zavedati vsega telesa. Zavedajte se vsega telesa, položaja rok in nog, zavedajte se hrbtenice ki podpira glavo in zavedajte se vašega stika s tlemi. Nadaljujte s tem nekaj trenutkov.</p>' +
                '<p>Nato se pričnite zavedati vseh občutkov v telesu. Zavedajte se hladu, toplote, vetra, bolečine, togosti, neudobja, srbenja. Zavedajte se vseh teh občutkov v telesu. Ne premikajte se le zavedajte se tega nekaj trenutkov. Nato se zavedajte samo glave in vseh občutkov v glavi in ničesar drugega. Nato nadaljujte k vratu. Nadaljujte k desni roki in desni nogi. Nato k levi roki in nadaljujte k levi nogi. Zavedajte se obeh rok in obeh nog. Nato nadaljujte k zadnjemu delu trupa in nato k prsim, nato trebuh. In končno celotno telo. Sprostite se. Lahko naredite še eno rundo.</p>' +
                '<p>Nato se pričnite zavedati svojega diha in telesa hkrati. Ne spreminjajte diha samo zavedajte se naravnega toka diha. Zavedajte se kako se z vdihom vaše telo polni s pomirjajočo se svetlobo z izdihom pa izdihujete vse napetosti iz svojega celotnega telesa. Vezmite si nekaj trenutkov, da se umirite in sprostite.</p>',

            uvodPrvi:
                '<p>Sedaj se začnite zavedati notranjega stanja, notranje tišine. To je na tej stopnji malo težje, zato si recite 3x: <i>"Zavedam se notranje tišine, ki je nedotakljiva od vsega kar je zunanjega."</i> Sedaj usmerite vso svojo pozornost k fizičnim občutkom, to je pritisk svojega telesa na tla, dotik oblačil na svoje telo,... Vso svojo pozornost usmerite v to. Do delajte vse dokler izgubite zanimanje. Morda boste čutili nekakšno posebno odmaknjenost, ampak pomembno je, da ko to začutite, da se nato preselite na zavedanje zunanjega okolja. Zavedajte se vsega okoli sebe. Zavedajte se vsega kar se dogaja zunaj vas pa naj vas to moti ali pa ne. Naj do tega zaznavanja pride brez kakršnega koli napora. Vso zaznavanje mora potekati nevtralno, to je zelo pomembno. Kljub temu, da pa obstaja veliko različnih vtisov, bo zvok najbolj zaznaven <sup>1</sup>.</p>' +
                '<p>Zavedajte se zunanjih zvokov. To so lahko različni zvoki, kot je na primer avto, ptice, radio, televizija, ljudje,... Karkoli je poslušajte to z nenavezanim zavedanjem, brez obsojanja, razmišljanja ali analiziranja. Samo slišite te zvoke brez razmišljanja od kod prihajajo ali od koga so. Če slišite lajež psa, ne razmišljajte o laježu psa... samo poslušajte zvok. Postavite se v vlogo gledalca, priče in ne se identificirat z nobenim zvokom. Recite si: <i>"Sem samo priča dogodkom in ti zvoki se me ne dotaknejo."</i> Nadaljujte z zavedanjem vseh zvokov v okolju, brez izbiranja. Samo sprejmajte. Delajte to nekaj minut.</p>' +
                '<p>Sedaj med vsemi zvoki izberite tistega, ki najbolj izstopa in usmerite svojo pozornost samo na ta zvok, vsi ostali pa niso pomembni. Po kakšni minuti izberite drug zvok in usmerite svojo pozornost samo na ta zvok. Ostanite pozorni, ostanite priča. Zavedajte se različnih zvokov po vrsti. In potem se spet istočasno zavedajte vseh zvokov, ki se pojavljajo. Razširite svoje zaznavanje na zunanji svet do popolnosti in slišite najmanjši zvok. Ne razmišljajte, samo zavedajte se zunanjih čutnih izkušenj.</p>' +
                '<p>Sedaj preusmerite svoje zavedanje na dihanje in čutite, kako dih priteka in odteka skozi nosnici v telo in iz njega. Zavedajte se dihanja nekaj minut. Potem spet preusmerite svoje zavedanje v zunanji svet in se spet pričnite zavedati zunanih zvokov. Tukaj lahko svoje zavedanje usmerite na vse zvoke ali pa si izberete zvok, ki je najbolj slišen in ga opazujete. Naj vas ne odnese navznoter in ne izgubite se v mislih. Poslušajte uro. Nekoga, ki kašlja. Nekoga, ki govori. Poslušajte veter, zvok tišine. Poslušajte zvoke, kot da vam je zunanji svet nekaj tujega.</p>' +
                '<p>Nato se spet nekaj minut zavedajte samo procesa dihanja. Ne zaznavajte zunanjega sveta ampak samo tok dihanja. Naj bo vsa vaša pozornost usmerjena k dihanju. In spet po nekem času spet usmerite svojo pozornost k zunanjim zvokom. Tako nadaljujte vse dokler imate čas.</p>',

            uvodDva:
                '<p>Vso svojo pozornost posvetite dihanju. Čutite, kako dih potuje skozi nosnici v pljuča in iz pljuč v celotno telo. In potem iz celotnega telesa, skozi pljuča in izven nosnici ven in s sabo nosi vse nečistoče in vse neprijetnosti, ki se v vas nabirajo. Posvetite vs svojo pozornost dihanju in dovolite, da se dih umiri, do te mere, da je navzven komaj vidno, da sploh dihate.</p>' +
                '<p>Sedaj se oserotočite na vdih in pri vdihu slišite mantro vdiha, ki je "<b>SO</b>". Mantra naj se vleče in potuje z vdihom. Čutite vibracijo mantre in svetlobo vdiha. Pri izdihu pa slišite mantro izdiha, ki je "<b>HAM</b>". Mantra potuje z izdihom. Skupaj tvorita mantro "<b>SOHAM</b>", ki je mantra diha. Prvi teden naredite 27 ponovitev, drugi teden 54, naslednja dva tedna pa po 108x.</p>',

            konec: '<p>Ko ste pripravljeni, da končate se zavedajte svojega dihanja. Pričnite se zavedati dihanja in kako pri vdihu vdihnete svetlobo, ki napolni vaše telo. Pri izdihu pa se vedno bolj zavedate svojega telesa. Zavedajte se diha in telesa hkrati. Naj bo ta proces vračanja ali zaključka počasen, ne hitite. Vzemite si čas, da začutite telo in dih. Po nekaj trenutkih se zavedajte položaja telesa in stičnih točk telesa s tlemi. Začnite se zavedati okolice v kateri ste. Počasi pričnite premikati glavo in roke. Pri izdihu odprite počasi oči. Kakšno minuto še sedite in počasi vstanite.</p>',

            dodatno: '<ol><li>Večkrat na dan si vzemite čas, se ustavite in preletite dan od zadnjega dogodka pa vse to prvega, ko ste se zbudili. Lahko to naredite tudi samo zvečer. Pomembno je, da se ne naprezate in ne silite samega sebe, da se vse spomnete. Dovolj je da na začetku ozavestite samo večje dogodke, kasneje čez dlje časa pa se spominjate še občutkov, morda vonjav in podobnega.</li>' +
                '<li>Vsak dan si vzemite čas za 30 zavestnih dihov. Vdih in izdih je en dih. Tudi preden zaspite se lahko zavestno ostredotočate na trebušno dihanje in se na ta način sproščate.</li>' +
                '<li>Vsako jutro, ko se zbudite, si recite, da bo to dan v katerem bo več zavedanja, kot pa dan pred njim. V ta namen si lahko pripravite kakšen listek ali nekaj, kar vas opominja, da živite bolj zavedno. Lahko uporabljate tudi kakšno aplikacijo (na primer "<i>Mindfulness Bell</i>") na telefonu, ki vas bo naključno opominjala, da postanete zavedni.</li></ol>',

            opombe: '<p>Opombe</p>' +
                '<ol><li>Če imate čas in voljo, si lahko te različne zvoke posnamete in posnetek uporabljate pri sadhani.</li>'

        }
    }
}
