export default {
    data() {
        return {
            naslov: "Sadhana X – Kolo sreče",

            priprava:
                '<p>Usedite se v udoben meditacijski položaj s prekrižanimi nogami, sede na stolu ali pa kako drugače. Poskrbite, da boste lahko ves čas meditacije sedeli udobno in brez kakršnih koli večjih neprijetnosti. Zaprite oči roke položite na kolena in se začnite zavedati vsega telesa. Zavedajte se vsega telesa, položaja rok in nog, zavedajte se hrbtenice ki podpira glavo in zavedajte se vašega stika s tlemi. Nadaljujte s tem nekaj trenutkov.</p>' +
                '<p>Nato se pričnite zavedati vseh občutkov v telesu. Zavedajte se hladu, toplote, vetra, bolečine, togosti, neudobja, srbenja. Zavedajte se vseh teh občutkov v telesu. Ne premikajte se le zavedajte se tega nekaj trenutkov. Nato se zavedajte samo glave in vseh občutkov v glavi in ničesar drugega. Nato nadaljujte k vratu. Nadaljujte k desni roki in desni nogi. Nato k levi roki in nadaljujte k levi nogi. Zavedajte se obeh rok in obeh nog. Nato nadaljujte k zadnjemu delu trupa in nato k prsim, nato trebuh. In končno celotno telo. Sprostite se. Lahko naredite še eno rundo <sup class="fw-bold">*<sup> 1</sup></sup>.</p>' +
                '<p>Nato se pričnite zavedati svojega diha in telesa hkrati. Ne spreminjajte diha samo zavedajte se naravnega toka diha. Zavedajte se, kako se z vsakim dihom vaše telo vse bolj sveti. Predstavljajte si telo kot svetlobo, ki z vsakim dihom vse bolj sveti in se dotika vsega okoli vas. Ta svetloba gre z vsakim dihom dlje in dlje, vse dokler ne prežame celoten svet in celo ves naš svet žari v beli svetlobi.</p>',

            anahata: '',

            navagrahaSadhana: '<p>Ponovite naslednjo mantro pozdrava vsem planetom enkrat na začetku in enkrat na koncu:</p><p><b>Om Aaditya Somaya Mangalaya Budhaya ca |<br>Guru Shukra Shanibhyashcharaya Rahave Ketave Namah ||</b></p><p>Vsako naslednjo mantro ponovite 11x:</p><dt>Surya (Sonce) - <b>Om Hrang Hring Hraung Sah Suryay Namah</b></dt><dd>Čutite moč, vitalnost, zmogljivosti, zdravje medtem ko izgovarjate to mantro.</dd><dt>Chandra (Luna) - <b>Om Shrang Shring Shraung Sah Chandray Namah</b></dt><dd>Čutite zadovoljstvo in duševni mir, mirno in hladno glavo.</dd><dt>Mangal (Mars) - <b>Om Krang Kring Kraung Sah Kujay Namah</b></dt><dd>Čutite pogum na vseh področjih.</dd><dt>Budh (Merkur) - <b>Om Brang Bring Braung Sah Budhay Namah</b></dt><dd>Čutite hitrost in intelektualno sposobnost svojega uma in znanje na vseh področjih.</dd><dt>Guru (Jupiter) - <b>Om Grang Gring Graung Sah Gurave Namah</b></dt><dd>Zavedajte se modrosti, čutite visok položaj v družbi, bogastvo in sposobnost biti pod kontrolo povsod.</dd><dt>Shukra (Venera) - <b>Om Drang Dring Draung Sah Shukray Nama</b></dt><dd>Čutite vsesplošno udobje, čudovitih odnosov s seboj in drugimi, zavedajte se bogastva v sebi in popolne sreče.</dd><dt>Shani (Saturn) - <b>Om Prang Pring Praung Sah Shanishchray Namah</b></dt><dd>Zavedajte se sebe kot višjega od ostalih vendar kljub temu ponižnega, začutite močno in stabilno kariero, bogastvo in dobro zdravje ter svojo duhovno rast.</dd><dt>Rahu - <b>Om Bhrang Bhring Bhraung Sah Rahave Namah</b></dt><dd>Zavedajte se svoje duhovnosti, širine, statusa, okultnega.</dd><dt>Kethu - <b>Om Strang String Straung Sah Ketave Namah</b></dt><dd>Zavedajte se svoje duhovnosti, izgube ega, ponosa in zavedajte se, da vas vaša pot vodi do samospoznanja in osvoboditve.</dd><b>Om Aaditya Somaya Mangalaya Budhaya cha |<br>Guru Shukra Shanibhyashcharaya Rahave Ketave Namah ||</b><br>',

            konec: '<p>Ko ste pripravljeni, da končate se zavedajte svojega telesa in vseh prijetnih občutkov. Predstavljajte si, kako se počasi pričenjate vračati v prostor od koder ste prišli. Zavedajte se, da se vračate nazaj. Naj bo ta proces počasen. Pričnite se zavedati dihanja in kako pri vdihu vdihnete svetlobo, ki napolni vaše telo. Pri izdihu se vedno bolj zavedate svojega telesa. Zavedajte se diha in telesa hkrati. Naj bo ta proces vračanja ali zaključka počasen, ne hitite. Vzemite si čas, da začutite telo in dih. Po nekaj trenutkih se zavedajte položaja telesa in stičnih točk telesa s tlemi. Začnite se zavedati okolice v kateri ste. Počasi pričnite premikati glavo in roke. Pri izdihu odprite počasi oči. Kakšno minuto še sedite in počasi vstanite.</p>',

        }
    }
}
