export default {
    data() {
        return {
            naslov: "Sadhana XVI – Trdnjava",

            priprava:
                '<p>Usedite se v udoben meditacijski položaj s prekrižanimi nogami, sede na stolu ali pa kako drugače. Poskrbite, da boste lahko ves čas meditacije sedeli udobno in brez kakršnih koli večjih neprijetnosti. Zaprite oči roke položite na kolena in se začnite zavedati vsega telesa. Zavedajte se vsega telesa, položaja rok in nog, zavedajte se hrbtenice ki podpira glavo in zavedajte se vašega stika s tlemi. Nadaljujte s tem nekaj trenutkov.</p>' +
                '<p>Nato se pričnite zavedati vseh občutkov v telesu. Zavedajte se hladu, toplote, vetra, bolečine, togosti, neudobja, srbenja. Zavedajte se vseh teh občutkov v telesu. Ne premikajte se le zavedajte se tega nekaj trenutkov. Nato se zavedajte samo glave in vseh občutkov v glavi in ničesar drugega. Nato nadaljujte k vratu. Nadaljujte k desni roki in desni nogi. Nato k levi roki in nadaljujte k levi nogi. Zavedajte se obeh rok in obeh nog. Nato nadaljujte k zadnjemu delu trupa in nato k prsim, nato trebuh. In končno celotno telo. Sprostite se. Lahko naredite še eno rundo.</p>' +
                '<p>Nato se pričnite zavedati svojega diha in telesa hkrati. Ne spreminjajte diha samo zavedajte se naravnega toka diha. Zavedajte se, kako se z vsakim dihom vaše telo vse bolj sveti. Predstavljajte si telo kot svetlobo, ki z vsakim dihom vse bolj sveti in se dotika vsega okoli vas. Ta svetloba gre z vsakim dihom dlje in dlje, vse dokler ne prežame celoten svet in celo ves naš svet žari v beli svetlobi.</p>',

            meditacijaElementi:
                '<p>Zavedajte se vsega. Zavedajte se sebe, svoje okolice. Zavedajte se vsega vesolja in vsega kar obstaja. Zavedajte se, da vse kar občutite, okusite, vidite, zaznavate in tako dalje, sestoji iz elementov. Zavedajte se elementa zemlje, trdnosti in in oprijemljivosti zemlje. Zavedajte se tega in 11x ponovite mantro <b>LAM</b>. "Občutite" ta element. Nato čutite kako se iz trdnosti element razgradi v vodo in se zavedajte kako celoten univerzum vsebuje tudi element vode. Občutite ta element in ponovite mantro <b>VAM</b>. Sedaj pojdite naprej in čutite prisotnost elementa ognja v vsemu in 11x ponovite mantro <b>RAM</b>. Nato čutite prisotnost elementa zraka in 11x ponovite mantro <b>YAM</b>. Temu sledi prisotnost prostora v vsemu in povsod in ponovite mantro <b>HAM</b>. Nato pa čutite, kako ste vsemu priča in čutite zavest in ponovite mantro <b>OM</b> 11x. Za trenutek se ustavite in bodite priča vsem elementom. Ste zavest, ki je priča energiji.</p>',

            meditacijaNapake: '<p>Najprej se ozrite nazaj na svoje življenje in priznajte svoje napake in napake. Vsi ljudje imajo nekaj podobnih osnovnih napak/napak, in sicer nevednost, arogantnost/ponos, navezanost, odpor itd. Toda potem, ko jih na splošno priznamo, je treba pogledati v specifično manifestacijo v svojem življenju. Posebej je treba pomisliti na trenutke, ko nekdo ni bil zvest svoji besedi ali svojemu namenu. Ko je nekdo škodoval drugemu z besedo, dejanjem ali celo mislijo. Razen teh osnovnih smernic bodo posebnosti edinstvene za vsako osebo in predstavljajo čase, ko oseba ni bila poštena. Pomembno je razumeti, da je to vaja integritete in ne morale. Na primer, nekoč, ko sem bil star morda 13 let, sem odšel iz boja. Konvencionalno (moralno) se to šteje za dobro in lahko celo rečem, da nasilje ni dobro in da nisem želel nikogar prizadeti itd. Toda resnica je bila, da sem odšel, ker me je bilo strah in to vem. Tako sem v svoji praksi to dejanje priznal kot strahopetnost. Prav tako je treba razumeti, da priznanje krivde v neki situaciji sploh ne pomeni, da bi to nujno naredili drugače. To je res zrela perspektiva, ki lahko reče, da bi, če bi bila priložnost, naredil enako, vendar še vedno vidim svojo napako v tem.</p><p>Prav tako morate poiskati stvari v svojem življenju, ki vas še vedno motijo, ne glede na to, ali predstavljajo kakšno napako. Če katera koli pretekla/trenutna situacija, oseba, spomin itd. prikliče močan odziv/čustvo, potem je z njo nekaj zastale energije. Pogosto je impulz teh stvari izogibanje, še posebej, če sproženi občutek ni prijeten ali prinaša zadrego. Vendar je treba odkrito dovoliti, da se porajajo vsa čustva. Osebo, situacijo itd. je treba priklicati v zavest, ne da bi se spet zataknili v celotno zgodbo o tem, ampak se raje ukvarjati neposredno z občutkom, ki ga vzbuja. Sedite z občutkom, ne da bi ga poskušali spremeniti, sedite odkrito in s sočutjem ter "povabite" ta občutek v ta prostor. Počasi (ali hitro) se bo ta energija osvobodila, ko bo povabljena v odprto sočutno prisotnost, in situacija ne bo več pekla ali vplivala. Pri tem je pomembno razumeti, da namen ni ponavljanje ali razmišljanje o preteklosti, temveč osvoboditev energije, ki je vezana. Razumite tudi, da so občutki vaši, zato ste vi odgovorni zanje, ne bi smeli imeti interesa biti žrtev in kriviti druge za to, kar se poraja v vas.</p><p>Ko končate s prakso čutite, kako ste bolj svobodni in lahki. Čutite, kako vas prežema svetloba in čutite, kako sprejemate preteklost!</p>',

            meditacijaTrdnjava: '<p>Recite si in resno mislite: "Pripravljen sem žrtvovati vse, da bi dosegel cilj svojega velikega potovanja." Sedaj vidite, kaj vse imate in česa vsega se oprijemate in si recite: "Če je volja univerzuma, da poruši vse, kar sem zgradil v svojem življenju, naj to stori in stori hitro." Sedaj vidite pred sabo vse, ki jih poznate (sorodnike, družino, prijatelje, sodelavce,...) in si recite: "Brez navezanosti na karkoli ali kogar koli. Ljubim vse, vendar sem se pripravljen ločiti od vseh navezanosti. Nič in nihče ni v moji lasti!"  Sedaj si predstavljajte vse te ljudi okoli sebe in vse niti, ki vas povezujejo. Nato si predstavljajte, kako se te niti prerežejo in vi ste svobodni! Nato si recite: "Zavedam se, da se z navezanostjo na stvari in ljudi nikoli ne bom mogel dvigniti v nebesa. Naj bo vse, kar je treba v meni uničiti, uničeno in za vedno izbrisano; tako se bom veselil z glasom groma in z bliskom bliska. Tako naj bo vedno." Čutite, kako imate vse kar potrebujete in da ste svobodni vseh navezanosti. Pošljite vso ljubezen vsem in zanjo ne zahtevajte nazaj ničesar. Svobodni ste!</p>',

            konec: '<p>Ko ste pripravljeni, da končate se zavedajte svojega telesa in vseh prijetnih občutkov. Predstavljajte si, kako se počasi pričenjate vračati v prostor od koder ste prišli. Zavedajte se, da se vračate nazaj. Naj bo ta proces počasen. Pričnite se zavedati dihanja in kako pri vdihu vdihnete svetlobo, ki napolni vaše telo. Pri izdihu se vedno bolj zavedate svojega telesa. Zavedajte se diha in telesa hkrati. Naj bo ta proces vračanja ali zaključka počasen, ne hitite. Vzemite si čas, da začutite telo in dih. Po nekaj trenutkih se zavedajte položaja telesa in stičnih točk telesa s tlemi. Začnite se zavedati okolice v kateri ste. Počasi pričnite premikati glavo in roke. Pri izdihu odprite počasi oči. Kakšno minuto še sedite in počasi vstanite.</p>',

        }
    }
}
