export default {
    data() {
        return {
            naslov: "Sadhana XVII – Zvezda",
            modrostGlavna: '"Ne meditiraj... BODI! Ne misli, da si... BODI! Ne razmišljaj o tem, da si... TI SI!"',

            priprava:
                '<p>Usedite se v udoben meditacijski položaj s prekrižanimi nogami, sede na stolu ali pa kako drugače. Poskrbite, da boste lahko ves čas meditacije sedeli udobno in brez kakršnih koli večjih neprijetnosti. Zaprite oči roke položite na kolena in se začnite zavedati vsega telesa. Zavedajte se vsega telesa, položaja rok in nog, zavedajte se hrbtenice ki podpira glavo in zavedajte se vašega stika s tlemi. Nadaljujte s tem nekaj trenutkov.</p>' +
                '<p>Nato se pričnite zavedati vseh občutkov v telesu. Zavedajte se hladu, toplote, vetra, bolečine, togosti, neudobja, srbenja. Zavedajte se vseh teh občutkov v telesu. Ne premikajte se le zavedajte se tega nekaj trenutkov. Nato se zavedajte samo glave in vseh občutkov v glavi in ničesar drugega. Nato nadaljujte k vratu. Nadaljujte k desni roki in desni nogi. Nato k levi roki in nadaljujte k levi nogi. Zavedajte se obeh rok in obeh nog. Nato nadaljujte k zadnjemu delu trupa in nato k prsim, nato trebuh. In končno celotno telo. Sprostite se. Lahko naredite še eno rundo.</p>' +
                '<p>Nato se pričnite zavedati svojega diha in telesa hkrati. Ne spreminjajte diha samo zavedajte se naravnega toka diha. Zavedajte se kako se z vdihom vaše telo polni s pomirjajočo se svetlobo z izdihom pa izdihujete vse napetosti iz svojega celotnega telesa. Vezmite si nekaj trenutkov, da se umirite in sprostite.</p>',

            starPranayamaOne: 'Dvignite desno roko pred glavo in dajte kazalec in sredinec skupaj in postavite blazinici prstov na center med obrvema. Nato s palcem zaprite desno nosnico. Petkrat vdihnite in izdihnite skozi levo nosnico. Ritem vdiha in izdiha naj bo normalen. Zavedajte se vsakega diha. Po petih dihih sprostite pritisk palca na desno nosnico, pritisnite s prstancem levo nosnico in zaprite pretok zraka. Petkrat vdihnite in izdihnite skozi desno nosnico in še naprej ohranjajte normalen ritem dihanja. Spustite roko in 5 krat dihajte skozi obe nosnici hkrati. To je ena runda. Vadite 5 rund ali 3 do 5 minut. Prepričajte se, da se ne sliši nobenega zvoka, ko gre zrak skozi nosnici.',
            starPranayamaTwo: 'Dvignite desno roko pred glavo in dajte kazalec in sredinec skupaj in postavite blazinici prstov na center med obrvema. Nato s palcem zaprite desno nosnico. Petkrat vdihnite skozi levo nosnico. Istočasno mentalno štejte "1, 2, 3, 4,.." dokler se vdih udobno ne konča. To je osnovno štetje. Dihajte globoko a se ne naprezajte. S prstancem zaprite levo nosnico, sprostite pritisk palca na desno nosnico in med izdihovanjem skozi desno nosnico istočasno štejte "1, 2, 3, 4,…". Čas vdiha in izdiha naj bo enak. Nato vdihnite skozi desno nosnico in istočasno štejte na enak način. Na koncu vdiha zaprite desno nosnico, odprite levo nosnico in izdihnite skozi levo nosnico ter štejte kot prej. In to je ena runda. Vadite 10 rund.',
            starPranayamaThree: 'Dvignite desno roko pred glavo in dajte kazalec in sredinec skupaj in postavite blazinici prstov na center med obrvema. Nato s palcem zaprite desno nosnico. Petkrat vdihnite skozi levo nosnico. Istočasno mentalno štejte "1, 2, 3, 4,.." dokler se vdih udobno ne konča. To je osnovno štetje. Dihajte globoko in sproščeno. Ne naprezajte se. S prstancem zaprite levo nosnico, sprostite pritisk palca na desno nosnico in med izdihovanjem skozi desno nosnico istočasno štejte "1, 2, 3, 4, 5, 6, 7, 8…". Tako je čas izdiha daljši od časa vdiha. Nato vdihnite skozi desno nosnico in istočasno štejte na enak način. Na koncu vdiha zaprite desno nosnico, odprite levo nosnico in izdihnite skozi levo nosnico ter štejte kot prej. In to je ena runda. Vadite 10 rund.',

            zacetniskiUm: '<p>Imeli začetniško umi preprosto pomeni, da se "zapletate" z drugimi ljudmi, dogodki, objekti in aktivnostmi, kot da je vse to prvič. Po navadi je to kar delate ali to kar mislite, pogojeno s preteklimi izkušnjami, prepričanji, presojanjem in zaključki. Ko delate stvari na isti način in izberete isto pot, kot ste to delali prej, ko se držite svojih starih vzorcev mišljenja in se odzivate na ostale ljudi, zamudite ogromno priložnosti, odkritij in vpogledov. Izberete ozko pot, kjer boste majn verjetno naleteli na nove ideje in na drugačne načine pogleda in razumevanja.</p><p>Namesto, da se odzivate na dogodke, mesta in na druge ljudi na enak način kot ste se prej, vam začetniški um omogoči, da izberete novo perspektivo in se odzovete na stvari kakršne so ta trenutek. Začetniški um vam ne odbija ali pa razvrednoti vašega preteklega znanja in izkušenj. Ampak vam preprosto predlaga, da obdržite odprt um na to, kako uporabiti svoje izkušnje na vsako situacijo. Začetniški um vam lahko pomaga da se umirite, da izkusite življenje v tem trenutku in to zato, ker iščete, da opazite nekaj novega v situaciji. Postavi vas v tukaj in zdaj, ker imate povečano zavedanje do tega, kaj se dogaja ta trenutek. To naredi življenje zanimivo in sveže. Ohranja vas pozorne, zavedne in voljne do učenja.</p><p>Kako izvajati: Izberite drugačno pot. Ali obstaja ista pot, po kateri greste po navadi? Poskušajte oditi 10 minut prej in izberite drugačno pot. S tem ko izberete drugačno pot vam dovoljuje/vas spodbuja da opazite nove stvari. To lahko celo preizkusite v trgovini. Če imate pot, po kateri greste po navadi po trgovini, jo tokrat spremenite. Vas bo upočasnilo, vendar nikoli ne veste, kakšne nove stvari boste odkrill. Morda celo zamenjajte trgovino in pojdite v drugo.</p><p>Poslušajte glasbo drugače. Z začetniškim umom lahko znano glasbo poslušate, kot, da je to prvič, ko ste jo slišali. Izberite najljubšo skladbo. Izberite del, ki ga po navadi ne slišite - ton, melodija, besedilo ali pa določen instrument. Sedaj poslušajte in sledite glasbi in se osredotočajte na nov element, ki ste ga izbrali. Če prav ste to skladbo slišali že velikokrat, ko jo poslušate z začetniškim umom, jo na novo doživite. Ste v trenutku.</p><p>Naučite se nekaj novega. To je lahko nov recept ali pa neka nova veščina, kot je jezik, kreativno pisanje, zidanje ali pa risanje. Lahko je šport, tenis ali pa badminton. Naučiti se nekaj novega je vsekakor dober način imeti začetniški um, ker se resnično lotite nečesa novega in to od začetka.</p><p>Vidite nekoga v drugačni luči. Pomislite na nekoga s katerim ste vedno s težavo shajali - družinski član ali pa sodelavec na primer. Dajte na stran vsa svoja prepričanja in mnenja o tej osebi in poskušajte v tej osebi videti nekaj novega. Iščite nekaj pozitivnega. Lahko je kakšna stvar v njihovi osebnosti, odnosu, kako vplivajo na druge ali pa nekaj o njihovem delu.</p>',

            konec: '<p>Ko ste pripravljeni, da končate se zavedajte svojega dihanja. Pričnite se zavedati dihanja in kako pri vdihu vdihnete svetlobo, ki napolni vaše telo. Pri izdihu pa se vedno bolj zavedate svojega telesa. Zavedajte se diha in telesa hkrati. Naj bo ta proces vračanja ali zaključka počasen, ne hitite. Vzemite si čas, da začutite telo in dih. Po nekaj trenutkih se zavedajte položaja telesa in stičnih točk telesa s tlemi. Začnite se zavedati okolice v kateri ste. Počasi pričnite premikati glavo in roke. Pri izdihu odprite počasi oči. Kakšno minuto še sedite in počasi vstanite.</p>',

            dodatno: 'Vzemite si čas nekajkrat na dan in se odločite, da boste izrekli kratko molitev vsak dan za nadangele Mihael, Gabriel, Uriel in Rafael. Molitve najdete na tej strani ali pa si ustvarite svojo ali pa najdete nekaj kar vam odgovarja kjerkoli želite.'
        }
    }
}
