export default {
    data() {
        return {
            naslov: "Sadhana XVII – Zvezda",
            modrostGlavna: '"Ne meditiraj... BODI! Ne misli, da si... BODI! Ne razmišljaj o tem, da si... TI SI!"',

            zacetniskiUm: '<p>Imeli začetniško umi preprosto pomeni, da se "zapletate" z drugimi ljudmi, dogodki, objekti in aktivnostmi, kot da je vse to prvič. Po navadi je to kar delate ali to kar mislite, pogojeno s preteklimi izkušnjami, prepričanji, presojanjem in zaključki. Ko delate stvari na isti način in izberete isto pot, kot ste to delali prej, ko se držite svojih starih vzorcev mišljenja in se odzivate na ostale ljudi, zamudite ogromno priložnosti, odkritij in vpogledov. Izberete ozko pot, kjer boste majn verjetno naleteli na nove ideje in na drugačne načine pogleda in razumevanja.</p><p>Namesto, da se odzivate na dogodke, mesta in na druge ljudi na enak način kot ste se prej, vam začetniški um omogoči, da izberete novo perspektivo in se odzovete na stvari kakršne so ta trenutek. Začetniški um vam ne odbija ali pa razvrednoti vašega preteklega znanja in izkušenj. Ampak vam preprosto predlaga, da obdržite odprt um na to, kako uporabiti svoje izkušnje na vsako situacijo. Začetniški um vam lahko pomaga da se umirite, da izkusite življenje v tem trenutku in to zato, ker iščete, da opazite nekaj novega v situaciji. Postavi vas v tukaj in zdaj, ker imate povečano zavedanje do tega, kaj se dogaja ta trenutek. To naredi življenje zanimivo in sveže. Ohranja vas pozorne, zavedne in voljne do učenja.</p><p>Kako izvajati: Izberite drugačno pot. Ali obstaja ista pot, po kateri greste po navadi? Poskušajte oditi 10 minut prej in izberite drugačno pot. S tem ko izberete drugačno pot vam dovoljuje/vas spodbuja da opazite nove stvari. To lahko celo preizkusite v trgovini. Če imate pot, po kateri greste po navadi po trgovini, jo tokrat spremenite. Vas bo upočasnilo, vendar nikoli ne veste, kakšne nove stvari boste odkrill. Morda celo zamenjajte trgovino in pojdite v drugo.</p><p>Poslušajte glasbo drugače. Z začetniškim umom lahko znano glasbo poslušate, kot, da je to prvič, ko ste jo slišali. Izberite najljubšo skladbo. Izberite del, ki ga po navadi ne slišite - ton, melodija, besedilo ali pa določen instrument. Sedaj poslušajte in sledite glasbi in se osredotočajte na nov element, ki ste ga izbrali. Če prav ste to skladbo slišali že velikokrat, ko jo poslušate z začetniškim umom, jo na novo doživite. Ste v trenutku.</p><p>Naučite se nekaj novega. To je lahko nov recept ali pa neka nova veščina, kot je jezik, kreativno pisanje, zidanje ali pa risanje. Lahko je šport, tenis ali pa badminton. Naučiti se nekaj novega je vsekakor dober način imeti začetniški um, ker se resnično lotite nečesa novega in to od začetka.</p><p>Vidite nekoga v drugačni luči. Pomislite na nekoga s katerim ste vedno s težavo shajali - družinski član ali pa sodelavec na primer. Dajte na stran vsa svoja prepričanja in mnenja o tej osebi in poskušajte v tej osebi videti nekaj novega. Iščite nekaj pozitivnega. Lahko je kakšna stvar v njihovi osebnosti, odnosu, kako vplivajo na druge ali pa nekaj o njihovem delu.</p>'
        }
    }
}
